// automatically generated by fbagen, do not modify

namespace MyGame.Schema
{

    public struct MutableVec3
    {

        public float X;

        public float Y;

        public float Z;

    }

    public class MutableMonster
    {

        public uint Id { get; set; }

        public MutableVec3 Pos { get; set; }

        public short Mana { get; set; }

        public short Hp { get; set; }

        public string Name { get; set; }

        public bool Friendly { get; set; }

        public byte[] Inventory { get; set; }

        public Color Color { get; set; }

        public Any Test { get; set; }

    }

    public class MutableWeapon
    {

        public uint Id { get; set; }

    }

    public class MutablePickup
    {

        public uint Id { get; set; }

    }

}